package configfile

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/BurntSushi/toml"
	"github.com/vinayprograms/agentkit/policy"
)

// full is an Options with every optional section switched on, so the
// generators' conditional branches are all exercised at once.
func full() Options {
	return Options{
		Workspace:        "/work",
		Provider:         ProviderAnthropic,
		Model:            "claude-sonnet-4-20250514",
		BaseURL:          "https://api.example/v1",
		Thinking:         "auto",
		CredentialMethod: "env",
		SmallLLMEnabled:  true,
		SmallLLMProvider: ProviderAnthropic,
		SmallLLMModel:    "claude-3-5-haiku-20241022",
		SmallLLMBaseURL:  "https://api.example/v1",
		UseProfiles:      true,
		Profiles: map[string]ProfileConfig{
			"fast":     {Model: "haiku", Thinking: "off"},
			"balanced": {Model: "sonnet"}, // no Thinking: exercises the omitted key
		},
		SecurityMode:    "paranoid",
		DefaultDeny:     true,
		AllowBash:       true,
		AllowWeb:        true,
		EnableTelemetry: true,
		EnableMCP:       true,
		MCPServers: map[string]MCPServerSetup{
			"memory": {Command: "npx", Args: []string{"-y", "server-memory"}, DeniedTools: []string{"forget"}},
			"fs":     {Command: "fsd"}, // no args, no denied tools
		},
	}
}

// generatedConfig is the subset of agent.toml the generator writes; decoding
// into it proves the emitted text parses and carries the expected values.
type generatedConfig struct {
	Agent struct {
		Workspace string `toml:"workspace"`
	} `toml:"agent"`
	LLM struct {
		Provider  string `toml:"provider"`
		Model     string `toml:"model"`
		MaxTokens int    `toml:"max_tokens"`
		BaseURL   string `toml:"base_url"`
		Thinking  string `toml:"thinking"`
		APIKeyEnv string `toml:"api_key_env"`
	} `toml:"llm"`
	SmallLLM struct {
		Provider string `toml:"provider"`
		Model    string `toml:"model"`
		BaseURL  string `toml:"base_url"`
	} `toml:"small_llm"`
	Profiles map[string]struct {
		Model    string `toml:"model"`
		Thinking string `toml:"thinking"`
	} `toml:"profiles"`
	Security struct {
		Mode string `toml:"mode"`
	} `toml:"security"`
	Telemetry struct {
		Enabled bool `toml:"enabled"`
	} `toml:"telemetry"`
	MCP struct {
		Servers map[string]struct {
			Command     string   `toml:"command"`
			Args        []string `toml:"args"`
			DeniedTools []string `toml:"denied_tools"`
		} `toml:"servers"`
	} `toml:"mcp"`
}

func TestAgentTOML_FullConfigRoundTrips(t *testing.T) {
	out := AgentTOML(full())
	var got generatedConfig
	if _, err := toml.Decode(out, &got); err != nil {
		t.Fatalf("decode: %v\n%s", err, out)
	}
	if got.Agent.Workspace != "/work" || got.LLM.Provider != ProviderAnthropic {
		t.Errorf("agent/llm section: %+v", got)
	}
	if got.LLM.BaseURL != "https://api.example/v1" || got.LLM.APIKeyEnv != "ANTHROPIC_API_KEY" {
		t.Errorf("llm base_url/api_key_env: %+v", got.LLM)
	}
	if got.SmallLLM.Model != "claude-3-5-haiku-20241022" || got.SmallLLM.BaseURL == "" {
		t.Errorf("small_llm: %+v", got.SmallLLM)
	}
	if got.Profiles["fast"].Thinking != "off" || got.Profiles["balanced"].Thinking != "" {
		t.Errorf("profiles: %+v", got.Profiles)
	}
	if got.Security.Mode != "paranoid" || !got.Telemetry.Enabled {
		t.Errorf("security/telemetry: %+v", got)
	}
	if !slices.Equal(got.MCP.Servers["memory"].Args, []string{"-y", "server-memory"}) ||
		!slices.Equal(got.MCP.Servers["memory"].DeniedTools, []string{"forget"}) {
		t.Errorf("mcp memory: %+v", got.MCP.Servers["memory"])
	}
	if got.MCP.Servers["fs"].Command != "fsd" || len(got.MCP.Servers["fs"].Args) != 0 {
		t.Errorf("mcp fs: %+v", got.MCP.Servers["fs"])
	}
	if !strings.Contains(out, "# Generated by: agent setup\n") {
		t.Errorf("default header credit missing:\n%s", out)
	}
}

func TestAgentTOML_MinimalConfigOmitsOptionalSections(t *testing.T) {
	out := AgentTOML(Options{Workspace: ".", Provider: ProviderOpenAI, Model: "gpt-4o", Thinking: "off"})
	for _, absent := range []string{"base_url", "api_key_env", "[small_llm]", "[profiles.", "[telemetry]", "[mcp"} {
		if strings.Contains(out, absent) {
			t.Errorf("minimal config must not emit %q:\n%s", absent, out)
		}
	}
	var got generatedConfig
	if _, err := toml.Decode(out, &got); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if got.LLM.MaxTokens != 4096 {
		t.Errorf("max_tokens = %d, want 4096", got.LLM.MaxTokens)
	}
}

func TestAgentTOML_MCPEnabledWithoutServersEmitsPlaceholder(t *testing.T) {
	out := AgentTOML(Options{Provider: ProviderOpenAI, EnableMCP: true})
	if !strings.Contains(out, "# [mcp.servers.memory]") {
		t.Errorf("expected commented placeholder:\n%s", out)
	}
	var got generatedConfig
	if _, err := toml.Decode(out, &got); err != nil {
		t.Fatalf("placeholder must stay commented out: %v", err)
	}
	if len(got.MCP.Servers) != 0 {
		t.Errorf("placeholder must not define servers: %+v", got.MCP.Servers)
	}
}

func TestAgentTOML_GeneratedByAndAPIKeyEnvOverrides(t *testing.T) {
	out := AgentTOML(Options{
		Provider:         ProviderCustom,
		CredentialMethod: "env",
		APIKeyEnv:        "MY_KEY",
		GeneratedBy:      "agent config init",
	})
	if !strings.Contains(out, "# Generated by: agent config init\n") {
		t.Errorf("GeneratedBy ignored:\n%s", out)
	}
	if !strings.Contains(out, `api_key_env = "MY_KEY"`) {
		t.Errorf("APIKeyEnv ignored:\n%s", out)
	}
}

func TestAgentTOML_UnknownProviderFallsBackToGenericEnvVar(t *testing.T) {
	out := AgentTOML(Options{Provider: "weird", CredentialMethod: "env"})
	if !strings.Contains(out, `api_key_env = "API_KEY"`) {
		t.Errorf("fallback env var missing:\n%s", out)
	}
}

// TestPolicyTOML_ParsesWithNoUnknownKeys is the contract that matters: every
// generated policy must load cleanly under the current policy schema.
func TestPolicyTOML_ParsesWithNoUnknownKeys(t *testing.T) {
	for _, o := range []Options{
		full(),
		{DefaultDeny: false, AllowBash: true, AllowWeb: true},
		{DefaultDeny: false, AllowBash: false, AllowWeb: false},
		{DefaultDeny: true, AllowBash: false, AllowWeb: false},
		{DefaultDeny: true, EnableMCP: true},
	} {
		content := PolicyTOML(o)
		pol, unknown, err := policy.FromTOMLWithUnknownKeys(content, "/work", "")
		if err != nil {
			t.Fatalf("parse %+v: %v\n%s", o, err, content)
		}
		if len(unknown) > 0 {
			t.Errorf("unknown keys %v for %+v:\n%s", unknown, o, content)
		}
		if pol.DefaultDeny != o.DefaultDeny {
			t.Errorf("default_deny = %v, want %v", pol.DefaultDeny, o.DefaultDeny)
		}
	}
}

func TestPolicyTOML_ToolSections(t *testing.T) {
	tests := []struct {
		name    string
		opts    Options
		want    []string
		notWant []string
	}{
		{
			name: "restrictive bash gets a deny list",
			opts: Options{DefaultDeny: true, AllowBash: true, AllowWeb: true},
			want: []string{"[tools.bash]", `deny = ["rm -rf *"`, "[tools.web_fetch]", "# allow = [\"github.com\""},
		},
		{
			name:    "permissive bash gets a recommendation comment",
			opts:    Options{DefaultDeny: false, AllowBash: true, AllowWeb: true},
			want:    []string{"[tools.bash]", "# Recommended for security:"},
			notWant: []string{`deny = ["rm -rf *"`},
		},
		{
			name:    "permissive without bash explains why it cannot be disabled",
			opts:    Options{DefaultDeny: false},
			want:    []string{"bash cannot be disabled individually", "web_search/web_fetch cannot be disabled individually"},
			notWant: []string{"[tools.bash]", "[tools.web_search]"},
		},
		{
			name:    "restrictive without bash simply omits it",
			opts:    Options{DefaultDeny: true},
			notWant: []string{"[tools.bash]", "[tools.web_search]", "cannot be disabled"},
		},
		{
			name: "mcp servers become allow patterns in sorted order",
			opts: Options{EnableMCP: true, MCPServers: map[string]MCPServerSetup{"zeta": {}, "alpha": {}}},
			want: []string{"[mcp]\nenabled = true\n", `allow = ["alpha:*", "zeta:*"]`},
		},
		{
			name: "mcp without servers keeps a commented example",
			opts: Options{EnableMCP: true},
			want: []string{`# allow = ["memory:*", "filesystem:read_file"]`},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			out := PolicyTOML(tt.opts)
			for _, w := range tt.want {
				if !strings.Contains(out, w) {
					t.Errorf("missing %q:\n%s", w, out)
				}
			}
			for _, w := range tt.notWant {
				if strings.Contains(out, w) {
					t.Errorf("unexpected %q:\n%s", w, out)
				}
			}
		})
	}
}

func TestApplyScenario(t *testing.T) {
	tests := []struct {
		scenario     string
		wantProvider string
		wantDeny     bool
		wantBash     bool
		wantMode     string
	}{
		{ScenarioLocal, ProviderOllamaLocal, false, true, "default"},
		{ScenarioDev, ProviderAnthropic, false, true, "default"},
		{ScenarioTeam, ProviderLiteLLM, true, true, "default"},
		{ScenarioProduction, ProviderLiteLLM, true, false, "paranoid"},
		{ScenarioDocker, ProviderLiteLLM, true, true, "default"},
	}
	for _, tt := range tests {
		t.Run(tt.scenario, func(t *testing.T) {
			o := Options{Scenario: tt.scenario}
			o.ApplyScenario()
			if o.Provider != tt.wantProvider || o.DefaultDeny != tt.wantDeny ||
				o.AllowBash != tt.wantBash || o.SecurityMode != tt.wantMode {
				t.Errorf("got %+v", o)
			}
		})
	}
	if o := (Options{Scenario: "nonsense", Provider: "keep"}); func() Options { o.ApplyScenario(); return o }().Provider != "keep" {
		t.Error("unknown scenario must leave Options untouched")
	}
	if !slices.Contains(Scenarios(), ScenarioProduction) || len(Scenarios()) != 5 {
		t.Errorf("Scenarios() = %v", Scenarios())
	}
	if o := (Options{Scenario: ScenarioDocker}); func() Options { o.ApplyScenario(); return o }().CredentialMethod != "env" {
		t.Error("docker scenario must select env credentials")
	}
}

func TestProviderDefaults(t *testing.T) {
	for _, p := range append(Providers(), "unknown-provider") {
		o := Options{Provider: p, SmallLLMProvider: p}
		o.SetDefaultModel()
		o.SetDefaultSmallModel()
		if p != ProviderCustom && p != "unknown-provider" && o.Model == "" {
			t.Errorf("%s: no default model", p)
		}
		if o.SmallLLMModel != o.Model && o.SmallLLMModel == "" {
			t.Errorf("%s: no default small model", p)
		}
		if NeedsBaseURL(p) && DefaultBaseURL(p) == "" && p != ProviderCustom {
			t.Errorf("%s needs a base URL but has no default", p)
		}
		if !NeedsBaseURL(p) && DefaultBaseURL(p) != "" {
			t.Errorf("%s: unexpected default base URL %q", p, DefaultBaseURL(p))
		}
	}
	// Custom is the escape hatch: it needs a base URL but cannot guess one.
	if !NeedsBaseURL(ProviderCustom) || DefaultBaseURL(ProviderCustom) != "" {
		t.Error("custom provider must need a base URL with no default")
	}
	// A small LLM on the same provider inherits the main base URL.
	o := Options{Provider: ProviderLiteLLM, BaseURL: "http://proxy/v1", SmallLLMProvider: ProviderLiteLLM}
	o.SetDefaultSmallModel()
	if o.SmallLLMBaseURL != "http://proxy/v1" {
		t.Errorf("small_llm base_url = %q", o.SmallLLMBaseURL)
	}
}

func TestDefaultEnvVar(t *testing.T) {
	want := map[string]string{
		ProviderAnthropic: "ANTHROPIC_API_KEY", ProviderOpenAI: "OPENAI_API_KEY",
		ProviderGoogle: "GOOGLE_API_KEY", ProviderMistral: "MISTRAL_API_KEY",
		ProviderGroq: "GROQ_API_KEY", ProviderXAI: "API_KEY",
	}
	for p, w := range want {
		if got := DefaultEnvVar(p); got != w {
			t.Errorf("DefaultEnvVar(%q) = %q, want %q", p, got, w)
		}
	}
}

func TestConfigureDefaultProfiles(t *testing.T) {
	for _, p := range []string{ProviderAnthropic, ProviderOpenAI, ProviderLiteLLM, ProviderOllamaLocal} {
		o := Options{Provider: p, Model: "m", Profiles: map[string]ProfileConfig{}}
		o.ConfigureDefaultProfiles()
		if _, ok := o.Profiles["fast"]; !ok {
			t.Errorf("%s: no fast profile, got %v", p, o.Profiles)
		}
	}
}

func TestWrite(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested")
	o := Options{Provider: ProviderOpenAI, Model: "gpt-4o", Workspace: "."}

	written, err := Write(dir, o, false)
	if err != nil {
		t.Fatalf("Write: %v", err)
	}
	want := []string{filepath.Join(dir, "agent.toml"), filepath.Join(dir, "policy.toml")}
	if !slices.Equal(written, want) {
		t.Errorf("written = %v, want %v", written, want)
	}
	for _, p := range written {
		info, err := os.Stat(p)
		if err != nil {
			t.Fatalf("stat %s: %v", p, err)
		}
		if info.Mode().Perm() != fileMode {
			t.Errorf("%s mode = %v, want %v", p, info.Mode().Perm(), os.FileMode(fileMode))
		}
	}

	// Without --force an existing file blocks the whole write, and every
	// blocking file is named.
	if _, err := Write(dir, o, false); err == nil {
		t.Fatal("second Write must refuse to overwrite")
	} else {
		for _, p := range want {
			if !strings.Contains(err.Error(), p) {
				t.Errorf("error must name %s: %v", p, err)
			}
		}
		if !strings.Contains(err.Error(), "--force") {
			t.Errorf("error must suggest --force: %v", err)
		}
	}

	o.Model = "gpt-5"
	if _, err := Write(dir, o, true); err != nil {
		t.Fatalf("forced Write: %v", err)
	}
	body, err := os.ReadFile(want[0])
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(body), "gpt-5") {
		t.Error("forced Write must overwrite")
	}
}

func TestWrite_Errors(t *testing.T) {
	root := t.TempDir()

	// A file where the directory should be: MkdirAll fails.
	blocked := filepath.Join(root, "notadir")
	if err := os.WriteFile(blocked, nil, 0644); err != nil {
		t.Fatal(err)
	}
	if _, err := Write(filepath.Join(blocked, "sub"), Options{}, false); err == nil {
		t.Error("Write into a non-directory must fail")
	}

	// A directory where policy.toml should be: the second file write fails
	// after the first succeeded, and the partial list comes back.
	dir := t.TempDir()
	if err := os.Mkdir(filepath.Join(dir, "policy.toml"), 0755); err != nil {
		t.Fatal(err)
	}
	written, err := Write(dir, Options{}, true)
	if err == nil {
		t.Fatal("blocked policy.toml must surface an error")
	}
	if !slices.Equal(written, []string{filepath.Join(dir, "agent.toml")}) {
		t.Errorf("partial write list = %v", written)
	}
}
