package configfile

import (
	"fmt"
	"slices"
	"strings"
)

// AgentTOML and PolicyTOML build TOML by hand rather than
// marshaling config.Config/policy.Policy. Both files interleave user-facing
// comments (recommendations, placeholders, explanations) between keys that a
// struct-tag marshaler cannot reproduce, and the round-trip tests
// (TestGeneratePolicyTOML_RoundTripsWithNoUnknownKeys) already guarantee the
// emitted keys parse cleanly under policy.FromTOMLWithUnknownKeys. Marshaling
// would drop the comments users diff against and gain nothing enforceable.

// AgentTOML renders o as the text of an agent.toml file.
func AgentTOML(o Options) string {
	var sb strings.Builder

	sb.WriteString("# Agent Configuration\n")
	sb.WriteString(fmt.Sprintf("# Generated by: %s\n\n", generatedBy(o)))

	// Agent section
	sb.WriteString("[agent]\n")
	sb.WriteString(fmt.Sprintf("workspace = \"%s\"\n\n", o.Workspace))

	// Main LLM
	sb.WriteString("# Main LLM\n")
	sb.WriteString("[llm]\n")
	sb.WriteString(fmt.Sprintf("provider = \"%s\"\n", o.Provider))
	sb.WriteString(fmt.Sprintf("model = \"%s\"\n", o.Model))
	sb.WriteString("max_tokens = 4096\n")
	if o.BaseURL != "" {
		sb.WriteString(fmt.Sprintf("base_url = \"%s\"\n", o.BaseURL))
	}
	sb.WriteString(fmt.Sprintf("thinking = \"%s\"\n", o.Thinking))
	if o.CredentialMethod == "env" {
		sb.WriteString(fmt.Sprintf("api_key_env = \"%s\"\n", envVarFor(o)))
	}
	sb.WriteString("\n")

	// Small LLM
	if o.SmallLLMEnabled {
		sb.WriteString("# Fast/cheap model for summarization, triage, memory extraction\n")
		sb.WriteString("[small_llm]\n")
		sb.WriteString(fmt.Sprintf("provider = \"%s\"\n", o.SmallLLMProvider))
		sb.WriteString(fmt.Sprintf("model = \"%s\"\n", o.SmallLLMModel))
		sb.WriteString("max_tokens = 1024\n")
		if o.SmallLLMBaseURL != "" {
			sb.WriteString(fmt.Sprintf("base_url = \"%s\"\n", o.SmallLLMBaseURL))
		}
		sb.WriteString("\n")
	}

	// Profiles
	if o.UseProfiles && len(o.Profiles) > 0 {
		sb.WriteString("# Capability Profiles\n")
		for name, profile := range o.Profiles {
			sb.WriteString(fmt.Sprintf("[profiles.%s]\n", name))
			sb.WriteString(fmt.Sprintf("model = \"%s\"\n", profile.Model))
			if profile.Thinking != "" {
				sb.WriteString(fmt.Sprintf("thinking = \"%s\"\n", profile.Thinking))
			}
			sb.WriteString("\n")
		}
	}

	// Security
	sb.WriteString("# Security Framework\n")
	sb.WriteString("[security]\n")
	sb.WriteString(fmt.Sprintf("mode = \"%s\"\n", o.SecurityMode))
	sb.WriteString("\n")

	// Telemetry
	if o.EnableTelemetry {
		sb.WriteString("# Telemetry\n")
		sb.WriteString("[telemetry]\n")
		sb.WriteString("enabled = true\n")
		sb.WriteString("protocol = \"otlp\"\n")
		sb.WriteString("# endpoint = \"http://localhost:4317\"\n")
		sb.WriteString("\n")
	}

	// MCP servers
	if o.EnableMCP && len(o.MCPServers) > 0 {
		sb.WriteString("# MCP Tool Servers\n")
		for name, srv := range o.MCPServers {
			sb.WriteString(fmt.Sprintf("[mcp.servers.%s]\n", name))
			sb.WriteString(fmt.Sprintf("command = \"%s\"\n", srv.Command))
			if len(srv.Args) > 0 {
				// Format args as TOML array
				quotedArgs := make([]string, len(srv.Args))
				for i, arg := range srv.Args {
					quotedArgs[i] = fmt.Sprintf("\"%s\"", arg)
				}
				sb.WriteString(fmt.Sprintf("args = [%s]\n", strings.Join(quotedArgs, ", ")))
			}
			if len(srv.DeniedTools) > 0 {
				quotedTools := make([]string, len(srv.DeniedTools))
				for i, tool := range srv.DeniedTools {
					quotedTools[i] = fmt.Sprintf("\"%s\"", tool)
				}
				sb.WriteString(fmt.Sprintf("denied_tools = [%s]\n", strings.Join(quotedTools, ", ")))
			}
			sb.WriteString("\n")
		}
	} else if o.EnableMCP {
		// Placeholder if MCP enabled but no servers configured
		sb.WriteString("# MCP Tool Servers\n")
		sb.WriteString("# [mcp.servers.memory]\n")
		sb.WriteString("# command = \"npx\"\n")
		sb.WriteString("# args = [\"-y\", \"@modelcontextprotocol/server-memory\"]\n")
		sb.WriteString("# denied_tools = []  # Tools to block from LLM\n\n")
	}

	return sb.String()
}

// PolicyTOML renders o as the text of a policy.toml file.
func PolicyTOML(o Options) string {
	var sb strings.Builder

	sb.WriteString("# Security Policy\n")
	sb.WriteString(fmt.Sprintf("# Generated by: %s\n\n", generatedBy(o)))

	// A tool is enabled when it has a [tools.<name>] table; with default_deny
	// unlisted tools are disabled, without it they are enabled.
	sb.WriteString(fmt.Sprintf("default_deny = %t\n", o.DefaultDeny))

	// Universal filesystem boundary — applies to all tools (read, write, edit, bash, etc.)
	sb.WriteString("allowed_dirs = [\"$WORKSPACE\", \"/tmp\"]\n\n")

	// File tools
	sb.WriteString("[tools.read]\n")
	sb.WriteString("deny = [\"**/.env\", \"**/*.key\", \"**/credentials.toml\"]\n\n")

	sb.WriteString("[tools.write]\n")
	sb.WriteString("deny = [\"agent.toml\", \"policy.toml\", \"credentials.toml\"]\n\n")

	// Bash
	if o.AllowBash {
		sb.WriteString("[tools.bash]\n")
		if o.DefaultDeny {
			sb.WriteString("deny = [\"rm -rf *\", \"sudo *\", \"curl * | bash\", \"chmod 777 *\", \"../*\", \"/*\"]\n")
		} else {
			sb.WriteString("# Recommended for security:\n")
			sb.WriteString("# deny = [\"docker\", \"kubectl\"]  # Add commands to block\n")
		}
		sb.WriteString("\n")
	} else if !o.DefaultDeny {
		sb.WriteString("# bash cannot be disabled individually while default_deny = false;\n")
		sb.WriteString("# set default_deny = true and list only the tools you want.\n\n")
	}

	// Web tools
	if o.AllowWeb {
		sb.WriteString("[tools.web_search]\n\n")

		sb.WriteString("[tools.web_fetch]\n")
		if o.DefaultDeny {
			sb.WriteString("# allow = [\"github.com\", \"*.github.io\", \"docs.python.org\"]\n")
		}
		sb.WriteString("\n")
	} else if !o.DefaultDeny {
		sb.WriteString("# web_search/web_fetch cannot be disabled individually while default_deny = false;\n")
		sb.WriteString("# set default_deny = true and list only the tools you want.\n\n")
	}

	// MCP policy - auto-generate allow patterns from configured servers
	if o.EnableMCP && len(o.MCPServers) > 0 {
		sb.WriteString("[mcp]\n")
		sb.WriteString("enabled = true\n")
		// Auto-allow all tools from configured servers (denied_tools in agent.toml handles filtering)
		sb.WriteString("allow = [")
		serverNames := sortedMCPNames(o.MCPServers)
		for i, name := range serverNames {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("\"%s:*\"", name))
		}
		sb.WriteString("]\n")
		sb.WriteString("# Note: per-server denied_tools in agent.toml filter tools from LLM\n")
		sb.WriteString("# This policy.toml [mcp] section is runtime defense-in-depth\n\n")
	} else if o.EnableMCP {
		sb.WriteString("[mcp]\n")
		sb.WriteString("enabled = true\n")
		sb.WriteString("# allow = [\"memory:*\", \"filesystem:read_file\"]\n\n")
	}

	return sb.String()
}

// envVarFor names the env var written as llm.api_key_env: the explicit
// override when the caller set one, else the provider's conventional var.
func envVarFor(o Options) string {
	if o.APIKeyEnv != "" {
		return o.APIKeyEnv
	}
	return DefaultEnvVar(o.Provider)
}

// sortedMCPNames returns the configured server names in a stable order so
// generated TOML does not churn between runs.
func sortedMCPNames(servers map[string]MCPServerSetup) []string {
	names := make([]string, 0, len(servers))
	for name := range servers {
		names = append(names, name)
	}
	slices.Sort(names)
	return names
}

// generatedBy names the command credited in the file header. It defaults to
// the setup wizard, the original and still most common generator.
func generatedBy(o Options) string {
	if o.GeneratedBy != "" {
		return o.GeneratedBy
	}
	return "agent setup"
}
