package setup

import (
	"fmt"
	"strings"
)

// generateAgentTOML and generatePolicyTOML build TOML by hand rather than
// marshaling config.Config/policy.Policy. Both files interleave user-facing
// comments (recommendations, placeholders, explanations) between keys that a
// struct-tag marshaler cannot reproduce, and the wizard's round-trip tests
// (TestGeneratePolicyTOML_RoundTripsWithNoUnknownKeys) already guarantee the
// emitted keys parse cleanly under policy.FromTOMLWithUnknownKeys. Marshaling
// would drop the comments users diff against and gain nothing enforceable.

func (m Model) generateAgentTOML() string {
	var sb strings.Builder

	sb.WriteString("# Agent Configuration\n")
	sb.WriteString("# Generated by: agent setup\n\n")

	// Agent section
	sb.WriteString("[agent]\n")
	sb.WriteString(fmt.Sprintf("workspace = \"%s\"\n\n", m.config.Workspace))

	// Main LLM
	sb.WriteString("# Main LLM\n")
	sb.WriteString("[llm]\n")
	sb.WriteString(fmt.Sprintf("provider = \"%s\"\n", m.config.Provider))
	sb.WriteString(fmt.Sprintf("model = \"%s\"\n", m.config.Model))
	sb.WriteString("max_tokens = 4096\n")
	if m.config.BaseURL != "" {
		sb.WriteString(fmt.Sprintf("base_url = \"%s\"\n", m.config.BaseURL))
	}
	sb.WriteString(fmt.Sprintf("thinking = \"%s\"\n", m.config.Thinking))
	if m.config.CredentialMethod == "env" {
		sb.WriteString(fmt.Sprintf("api_key_env = \"%s\"\n", getDefaultEnvVar(m.config.Provider)))
	}
	sb.WriteString("\n")

	// Small LLM
	if m.config.SmallLLMEnabled {
		sb.WriteString("# Fast/cheap model for summarization, triage, memory extraction\n")
		sb.WriteString("[small_llm]\n")
		sb.WriteString(fmt.Sprintf("provider = \"%s\"\n", m.config.SmallLLMProvider))
		sb.WriteString(fmt.Sprintf("model = \"%s\"\n", m.config.SmallLLMModel))
		sb.WriteString("max_tokens = 1024\n")
		if m.config.SmallLLMBaseURL != "" {
			sb.WriteString(fmt.Sprintf("base_url = \"%s\"\n", m.config.SmallLLMBaseURL))
		}
		sb.WriteString("\n")
	}

	// Profiles
	if m.config.UseProfiles && len(m.config.Profiles) > 0 {
		sb.WriteString("# Capability Profiles\n")
		for name, profile := range m.config.Profiles {
			sb.WriteString(fmt.Sprintf("[profiles.%s]\n", name))
			sb.WriteString(fmt.Sprintf("model = \"%s\"\n", profile.Model))
			if profile.Thinking != "" {
				sb.WriteString(fmt.Sprintf("thinking = \"%s\"\n", profile.Thinking))
			}
			sb.WriteString("\n")
		}
	}

	// Security
	sb.WriteString("# Security Framework\n")
	sb.WriteString("[security]\n")
	sb.WriteString(fmt.Sprintf("mode = \"%s\"\n", m.config.SecurityMode))
	sb.WriteString("\n")

	// Telemetry
	if m.config.EnableTelemetry {
		sb.WriteString("# Telemetry\n")
		sb.WriteString("[telemetry]\n")
		sb.WriteString("enabled = true\n")
		sb.WriteString("protocol = \"otlp\"\n")
		sb.WriteString("# endpoint = \"http://localhost:4317\"\n")
		sb.WriteString("\n")
	}

	// MCP servers
	if m.config.EnableMCP && len(m.config.MCPServers) > 0 {
		sb.WriteString("# MCP Tool Servers\n")
		for name, srv := range m.config.MCPServers {
			sb.WriteString(fmt.Sprintf("[mcp.servers.%s]\n", name))
			sb.WriteString(fmt.Sprintf("command = \"%s\"\n", srv.Command))
			if len(srv.Args) > 0 {
				// Format args as TOML array
				quotedArgs := make([]string, len(srv.Args))
				for i, arg := range srv.Args {
					quotedArgs[i] = fmt.Sprintf("\"%s\"", arg)
				}
				sb.WriteString(fmt.Sprintf("args = [%s]\n", strings.Join(quotedArgs, ", ")))
			}
			if len(srv.DeniedTools) > 0 {
				quotedTools := make([]string, len(srv.DeniedTools))
				for i, tool := range srv.DeniedTools {
					quotedTools[i] = fmt.Sprintf("\"%s\"", tool)
				}
				sb.WriteString(fmt.Sprintf("denied_tools = [%s]\n", strings.Join(quotedTools, ", ")))
			}
			sb.WriteString("\n")
		}
	} else if m.config.EnableMCP {
		// Placeholder if MCP enabled but no servers configured
		sb.WriteString("# MCP Tool Servers\n")
		sb.WriteString("# [mcp.servers.memory]\n")
		sb.WriteString("# command = \"npx\"\n")
		sb.WriteString("# args = [\"-y\", \"@modelcontextprotocol/server-memory\"]\n")
		sb.WriteString("# denied_tools = []  # Tools to block from LLM\n\n")
	}

	return sb.String()
}

func (m Model) generatePolicyTOML() string {
	var sb strings.Builder

	sb.WriteString("# Security Policy\n")
	sb.WriteString("# Generated by: agent setup\n\n")

	// A tool is enabled when it has a [tools.<name>] table; with default_deny
	// unlisted tools are disabled, without it they are enabled.
	sb.WriteString(fmt.Sprintf("default_deny = %t\n", m.config.DefaultDeny))

	// Universal filesystem boundary — applies to all tools (read, write, edit, bash, etc.)
	sb.WriteString("allowed_dirs = [\"$WORKSPACE\", \"/tmp\"]\n\n")

	// File tools
	sb.WriteString("[tools.read]\n")
	sb.WriteString("deny = [\"**/.env\", \"**/*.key\", \"**/credentials.toml\"]\n\n")

	sb.WriteString("[tools.write]\n")
	sb.WriteString("deny = [\"agent.toml\", \"policy.toml\", \"credentials.toml\"]\n\n")

	// Bash
	if m.config.AllowBash {
		sb.WriteString("[tools.bash]\n")
		if m.config.DefaultDeny {
			sb.WriteString("deny = [\"rm -rf *\", \"sudo *\", \"curl * | bash\", \"chmod 777 *\", \"../*\", \"/*\"]\n")
		} else {
			sb.WriteString("# Recommended for security:\n")
			sb.WriteString("# deny = [\"docker\", \"kubectl\"]  # Add commands to block\n")
		}
		sb.WriteString("\n")
	} else if !m.config.DefaultDeny {
		sb.WriteString("# bash cannot be disabled individually while default_deny = false;\n")
		sb.WriteString("# set default_deny = true and list only the tools you want.\n\n")
	}

	// Web tools
	if m.config.AllowWeb {
		sb.WriteString("[tools.web_search]\n\n")

		sb.WriteString("[tools.web_fetch]\n")
		if m.config.DefaultDeny {
			sb.WriteString("# allow = [\"github.com\", \"*.github.io\", \"docs.python.org\"]\n")
		}
		sb.WriteString("\n")
	} else if !m.config.DefaultDeny {
		sb.WriteString("# web_search/web_fetch cannot be disabled individually while default_deny = false;\n")
		sb.WriteString("# set default_deny = true and list only the tools you want.\n\n")
	}

	// MCP policy - auto-generate allow patterns from configured servers
	if m.config.EnableMCP && len(m.config.MCPServers) > 0 {
		sb.WriteString("[mcp]\n")
		sb.WriteString("enabled = true\n")
		// Auto-allow all tools from configured servers (denied_tools in agent.toml handles filtering)
		sb.WriteString("allow = [")
		serverNames := m.getSortedMCPServerNames()
		for i, name := range serverNames {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("\"%s:*\"", name))
		}
		sb.WriteString("]\n")
		sb.WriteString("# Note: per-server denied_tools in agent.toml filter tools from LLM\n")
		sb.WriteString("# This policy.toml [mcp] section is runtime defense-in-depth\n\n")
	} else if m.config.EnableMCP {
		sb.WriteString("[mcp]\n")
		sb.WriteString("enabled = true\n")
		sb.WriteString("# allow = [\"memory:*\", \"filesystem:read_file\"]\n\n")
	}

	return sb.String()
}
